### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/ExcusesRoberttovarv#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Buen trabajo @Roberttovarv ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- ¡Muy bien resuelto! ¡Muy original!
- Para seguir practicando JS, te recomiendo duplicar el repositorio y usar el método `.map` para la lógica de tu proyecto (aunque creo que ya habías estado trabajando el `map( )` en otros proyectos).
- El `console.log( )` es útil para propósitos de desarrollo y depuración, ya que permite imprimir información en la consola del navegador para ayudar a entender lo que está ocurriendo en el código, pero es recomendable eliminarlos para evitar imprimir información innecesaria en la consola del navegador del usuario final 
![Captura de pantalla de 2024-03-28 17-53-36](https://github.com/4GeeksAcademy/ExcusesRoberttovarv/assets/139759297/0e095b8c-a38a-4070-8d20-17cfcff78c0c)

**Comment by Roberttovarv** [comment]
Hola Eduardo, 

Apunto lo que me dices del console log.

Los maps necesito practicarlos más así que ten en cuenta que seguiré dándole.

Gracias!
